#############################################################################
# Makefile for building: OctoBTT
# Generated by qmake (3.1) (Qt 5.11.3)
# Project:  OctoBQPi.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile OctoBTT.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtSvg -isystem /usr/include/arm-linux-gnueabihf/qt5/QtWidgets -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I. -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = OctoBTT1.0.0
DISTDIR = /home/pi/OctoBTT/.tmp/OctoBTT1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Svg -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGLESv2 -lpthread -latomic 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = cameradialog.cpp \
		controlpanel.cpp \
		filedialog.cpp \
		main.cpp \
		mainwindow.cpp \
		materialctrlpanel.cpp \
		octonetwork.cpp \
		selectfile.cpp \
		url_camera.cpp qrc_assets.cpp \
		moc_cameradialog.cpp \
		moc_controlpanel.cpp \
		moc_filedialog.cpp \
		moc_mainwindow.cpp \
		moc_materialctrlpanel.cpp \
		moc_selectfile.cpp \
		moc_url_camera.cpp
OBJECTS       = cameradialog.o \
		controlpanel.o \
		filedialog.o \
		main.o \
		mainwindow.o \
		materialctrlpanel.o \
		octonetwork.o \
		selectfile.o \
		url_camera.o \
		qrc_assets.o \
		moc_cameradialog.o \
		moc_controlpanel.o \
		moc_filedialog.o \
		moc_mainwindow.o \
		moc_materialctrlpanel.o \
		moc_selectfile.o \
		moc_url_camera.o
DIST          = README_zh.md \
		start.sh \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-
